name    'saz-vim'
version '1.0.0'
source 'UNKNOWN'
author 'saz'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'Manage VIM via Puppet'
project_page 'https://github.com/saz/puppet-vim'
