name    'diegolima-vim'
version '2.0.2'
author 'diegolima'
license 'Apache License, Version 2.0'
summary 'Manage VIM via puppet.'
description 'Vim is an advanced text editor that seeks to provide the power of the de-facto Unix editor Vi, with a more complete feature set. This module aims to enable easy installation and configuration of VIM through class parameters on different platforms, in a way that the administrator can easily set it up differently according to need and/or personal taste.'
project_page 'https://github.com/diegolima/puppet-vim'
source 'This module was forked from the one originally written by Saz (https://github.com/saz/puppet-vim)'
